version = 1

[update]
## Keep every PR up to date with main
always = true 
require_automerge_label = false 
ignored_usernames = ["dependabot", "renovate"]


[merge]
automerge_label = "automerge"
prioritize_ready_to_merge = true

[merge.automerge_dependencies]
# auto merge all PRs opened by dependency management that are "minor" or "patch" version upgrades. "major" version upgrades will be ignored.
versions = ["minor", "patch"]
usernames = ["dependabot", "renovate"]


[approve]
auto_approve_usernames = ["dependabot", "renovate"]

[merge.message]
# use title of PR for merge commit.
title = "pull_request_title" # default: "github_default"

# use body of PR for merge commit.
# body = "pull_request_body" # default: "github_default"

# add the PR number to the merge commit title, like GitHub.
include_pr_number = true # default: true

# use the default markdown content of the PR for the merge commit.
body_type = "markdown" # default: "markdown"

# remove html comments to auto remove PR templates.
strip_html_comments = true # default: false
