on:
  pull_request_review:
    types: [submitted]
    branches:
      - develop

jobs:
  ff-sync:
    name: Auto merge main -> develop sync using fast forward
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fast Forward PR
        id: ff-pr
        uses: endre-spotlab/fast-forward-js-action@2.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          production_branch: "main"
          staging_branch: "develop"
