name: Fast-Forward Merge Kick-off
on:
  pull_request_review:
    types: [submitted]
    branches:
      - develop
  check_suite:
    types: [completed]
    branches:
      - develop

jobs:
  merge-check:
    name: "Check to see if PR can merge"
    runs-on: ubuntu-latest
    steps:
      - id: run-check
        uses: joekarow/can-pr-merge-action@main
        with:
          pr: ${{ github.event.check_suite[pull_requests].[0] || github.event.pull_request_review.pull_request.number}}
    outputs:
      ok_to_merge: ${{steps.run-check.outputs.ok_to_merge }}
  ff-start:
    name: "Kick merge workflow"
    needs: merge-check
    runs-on: ubuntu-latest
    steps:
      - run: gh workflow run ff-merge-main-dev.yml
