name: Run Linter
on:
  pull_request:
  push:

jobs:
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Identify package manager
        id: pkgman
        uses: joekarow/act-which-package-mgr@main
      - name: Setup node env
        if: ${{ success() }}
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: ${{ steps.pkgman.outputs.package_manager }}
      - name: Install package manager globally
        if: ${{steps.pkgman.outputs.package_manager != 'npm' }}
        run: npm -g install ${{ steps.pkgman.outputs.package_manager }}
      - name: Install dependencies
        if: ${{ success() }}
        uses: jaid/action-npm-install@v1.2.4
        with:
          packageManager: ${{ steps.pkgman.outputs.package_manager }}
      - name: Run lint step
        if: ${{ success() }}
        run: npx ${{ steps.pkgman.outputs.package_manager }} run lint
