name: Run Linter
on:
  pull_request:
  push:

jobs:
  get_sha:
    runs-on: ubuntu-latest
    name: Workflow checks
    steps:
      - if: ${{ github.event == 'push' }}
        id: push
        run: echo "::set-output name=sha::${{github.sha}}"
      - if: ${{ github.event == 'pull_request'}}
        id: pr
        run: echo "::set-output name=sha::${{github.event.pull_request.head.sha}}"
    outputs:
      sha: ${{steps.push.outputs.sha || steps.pr.outputs.sha}}
  lint:
    name: Run Linter
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ needs.get_sha.outputs.sha }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Identify package manager
        id: pkgman
        uses: joekarow/act-which-package-mgr@main
      - name: Install package managers globally
        run: npm -g install pnpm yarn
      - name: Setup node env
        if: ${{ success() }}
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: ${{ steps.pkgman.outputs.package_manager }}
      - name: Install dependencies
        if: ${{ success() }}
        uses: jaid/action-npm-install@v1.2.4
        with:
          packageManager: ${{ steps.pkgman.outputs.package_manager }}
      - name: Run lint step
        if: ${{ success() }}
        run: npx ${{ steps.pkgman.outputs.package_manager }} run lint
